/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GamesScattegoryIndexRouteImport } from './routes/games/scattegory/index'
import { Route as GamesNflIndexRouteImport } from './routes/games/nfl/index'
import { Route as Games1501IndexRouteImport } from './routes/games/1501/index'
import { Route as GamesScattegoryRoomIdRouteImport } from './routes/games/scattegory/$roomId'
import { Route as GamesNflDartsaiIndexRouteImport } from './routes/games/nfl/dartsai/index'
import { Route as GamesNflDartsIndexRouteImport } from './routes/games/nfl/darts/index'
import { Route as Games1501PlayIndexRouteImport } from './routes/games/1501/play/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesScattegoryIndexRoute = GamesScattegoryIndexRouteImport.update({
  id: '/games/scattegory/',
  path: '/games/scattegory/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesNflIndexRoute = GamesNflIndexRouteImport.update({
  id: '/games/nfl/',
  path: '/games/nfl/',
  getParentRoute: () => rootRouteImport,
} as any)
const Games1501IndexRoute = Games1501IndexRouteImport.update({
  id: '/games/1501/',
  path: '/games/1501/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesScattegoryRoomIdRoute = GamesScattegoryRoomIdRouteImport.update({
  id: '/games/scattegory/$roomId',
  path: '/games/scattegory/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesNflDartsaiIndexRoute = GamesNflDartsaiIndexRouteImport.update({
  id: '/games/nfl/dartsai/',
  path: '/games/nfl/dartsai/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesNflDartsIndexRoute = GamesNflDartsIndexRouteImport.update({
  id: '/games/nfl/darts/',
  path: '/games/nfl/darts/',
  getParentRoute: () => rootRouteImport,
} as any)
const Games1501PlayIndexRoute = Games1501PlayIndexRouteImport.update({
  id: '/games/1501/play/',
  path: '/games/1501/play/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/games/scattegory/$roomId': typeof GamesScattegoryRoomIdRoute
  '/games/1501/': typeof Games1501IndexRoute
  '/games/nfl/': typeof GamesNflIndexRoute
  '/games/scattegory/': typeof GamesScattegoryIndexRoute
  '/games/1501/play/': typeof Games1501PlayIndexRoute
  '/games/nfl/darts/': typeof GamesNflDartsIndexRoute
  '/games/nfl/dartsai/': typeof GamesNflDartsaiIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/games/scattegory/$roomId': typeof GamesScattegoryRoomIdRoute
  '/games/1501': typeof Games1501IndexRoute
  '/games/nfl': typeof GamesNflIndexRoute
  '/games/scattegory': typeof GamesScattegoryIndexRoute
  '/games/1501/play': typeof Games1501PlayIndexRoute
  '/games/nfl/darts': typeof GamesNflDartsIndexRoute
  '/games/nfl/dartsai': typeof GamesNflDartsaiIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/games/scattegory/$roomId': typeof GamesScattegoryRoomIdRoute
  '/games/1501/': typeof Games1501IndexRoute
  '/games/nfl/': typeof GamesNflIndexRoute
  '/games/scattegory/': typeof GamesScattegoryIndexRoute
  '/games/1501/play/': typeof Games1501PlayIndexRoute
  '/games/nfl/darts/': typeof GamesNflDartsIndexRoute
  '/games/nfl/dartsai/': typeof GamesNflDartsaiIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/games/scattegory/$roomId'
    | '/games/1501/'
    | '/games/nfl/'
    | '/games/scattegory/'
    | '/games/1501/play/'
    | '/games/nfl/darts/'
    | '/games/nfl/dartsai/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/games/scattegory/$roomId'
    | '/games/1501'
    | '/games/nfl'
    | '/games/scattegory'
    | '/games/1501/play'
    | '/games/nfl/darts'
    | '/games/nfl/dartsai'
  id:
    | '__root__'
    | '/'
    | '/games/scattegory/$roomId'
    | '/games/1501/'
    | '/games/nfl/'
    | '/games/scattegory/'
    | '/games/1501/play/'
    | '/games/nfl/darts/'
    | '/games/nfl/dartsai/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GamesScattegoryRoomIdRoute: typeof GamesScattegoryRoomIdRoute
  Games1501IndexRoute: typeof Games1501IndexRoute
  GamesNflIndexRoute: typeof GamesNflIndexRoute
  GamesScattegoryIndexRoute: typeof GamesScattegoryIndexRoute
  Games1501PlayIndexRoute: typeof Games1501PlayIndexRoute
  GamesNflDartsIndexRoute: typeof GamesNflDartsIndexRoute
  GamesNflDartsaiIndexRoute: typeof GamesNflDartsaiIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/scattegory/': {
      id: '/games/scattegory/'
      path: '/games/scattegory'
      fullPath: '/games/scattegory/'
      preLoaderRoute: typeof GamesScattegoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/nfl/': {
      id: '/games/nfl/'
      path: '/games/nfl'
      fullPath: '/games/nfl/'
      preLoaderRoute: typeof GamesNflIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/1501/': {
      id: '/games/1501/'
      path: '/games/1501'
      fullPath: '/games/1501/'
      preLoaderRoute: typeof Games1501IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/scattegory/$roomId': {
      id: '/games/scattegory/$roomId'
      path: '/games/scattegory/$roomId'
      fullPath: '/games/scattegory/$roomId'
      preLoaderRoute: typeof GamesScattegoryRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/nfl/dartsai/': {
      id: '/games/nfl/dartsai/'
      path: '/games/nfl/dartsai'
      fullPath: '/games/nfl/dartsai/'
      preLoaderRoute: typeof GamesNflDartsaiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/nfl/darts/': {
      id: '/games/nfl/darts/'
      path: '/games/nfl/darts'
      fullPath: '/games/nfl/darts/'
      preLoaderRoute: typeof GamesNflDartsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/1501/play/': {
      id: '/games/1501/play/'
      path: '/games/1501/play'
      fullPath: '/games/1501/play/'
      preLoaderRoute: typeof Games1501PlayIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GamesScattegoryRoomIdRoute: GamesScattegoryRoomIdRoute,
  Games1501IndexRoute: Games1501IndexRoute,
  GamesNflIndexRoute: GamesNflIndexRoute,
  GamesScattegoryIndexRoute: GamesScattegoryIndexRoute,
  Games1501PlayIndexRoute: Games1501PlayIndexRoute,
  GamesNflDartsIndexRoute: GamesNflDartsIndexRoute,
  GamesNflDartsaiIndexRoute: GamesNflDartsaiIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
